### ISSUE TITLE
Configuration: handle environment variables referenced in configuration

### ISSUE THREAD

**Issue by eledhwen** [lumio-medical/lumio-vault#5]
Make it so that configuration files and `Definitions` instances can reference environment variables.

The syntax should likely be something along the lines of:

```yml

variables:
    some_var: "$SOME_ENV_VARIABLE"
    some_other_var: "${SOME_OTHER_ENV_VARIABLE}"

services:
    some_service:
        class: "com.lumio.MyClass"
        constructor:
            - "##some.var##"
            - "${ENV_VAR}"
```
