### ISSUE TITLE
Configuration: Support for configuration extensions

### ISSUE THREAD

**Issue by eledhwen** [lumio-medical/lumio-vault#6]
_WIP_: need to work on the specs

Create a system for declaring configuration extensions that can:

* allow the declaration of custom configuration sections
* manipulate the `Definitions` instance before compilation
* manipulate the `Cellar` instance after compilation

For instance, an extension could be so that:

```yml
imports:
    - "some/dependency.yml"
    # Module configuration can be imported & extended
    # stays.yml could define a mapping for stays, while another could define the patients mapping, for instance.
    - "etl/mapping/stays.yml"

variables:
    my_format: "Y/m/d"

services:
    myservice:
        class: com.lumio.MyClass

my_etl:
    # Can reference variables
    date_format: "##my_format##"
    mapping:
        # Either reference an external file
        prescription: "com/lumiomedical/dataframe/prescriptions.json"
        # Or define it inline
        medications:
            name: "Medications dataset"
            separator: ","
            has_header: true
            column_count: 81
            charset: "utf-8"
            ...
```
